apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-with-merge

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

#patchesStrategicMerge:
# 'patches' keyword senses patch types below are strategic merge
patches:
- patch-selector.yaml
- patch-labels.yaml
- patch-anti-affinity.yaml
- patch-container-env-usingreplace.yaml
#- patch-container-env-usingdelete.yaml

# specifying strategic merge patch inline (same as patch-selector.yaml)
# but also means you cannot match yaml indentation of target
#- |-
#  apiVersion: apps/v1
#  kind: Deployment
#  metadata:
#    name: simple-deployment
#  spec:
#    selector:
#      matchLabels:
#        $patch: replace
#        tier: api
#        app: simple-deployment
